services:
  - type: web
    name: InterviewMaster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=5000
    envVars:
      - key: FLASK_APP
        value: flasker
